### ISSUE TITLE
Resets with active low logic level

### ISSUE THREAD

**Issue by Reisswolf** [alexforencich/cocotbext-axi#11]
I believe that the current implementation only supports active high reset implementations. In an active low case the simulation seems to stall in the reset section. I think a parameter should be introduced that specifies the reset polarity so that both cases work depending on the configuration. 
I wanted to discuss this issue before jumping the gun and creating a pull-request. What are your thoughts?

**Comment by alexforencich** [comment]
I'm in the process of completely rebuilding the reset implementation.  The new implementation at its core supports both polarities, but I'm not sure the best way to expose that at the top-level.  Might just need to add another parameter to the constructor, I will ask about this on the cocotb gitter to see if anyone has any better ideas.

**Comment by alexforencich** [comment]
Also, I should mention that with the current setup, resets really don't work correctly, so you're better off leaving it disconnected until I get it fixed up properly.

**Comment by catkira** [comment]
I have the same issue, I want to implement a core that is compatible to Xilinx AXIS cores. They use active low reset.
The sink never receives data if I do
self.sink = AxiStreamSink(dut, "m_axis", dut.clk, dut.nrst)  

doing
self.sink = AxiStreamSink(dut, "m_axis", dut.clk, not dut.nrst)  
does not work

for now I disconnected the reset, so the simulation does not freeze.

**Comment by alexforencich** [comment]
The latest release of cocotbext-axi adds the `reset_active_level` parameter to the constructors.  Set this to `False` for an active-low reset.
