### ISSUE TITLE
[Question] _init_x = True

### ISSUE THREAD

**Issue by Botnic** [alexforencich/cocotbext-axi#24]
In class AxiStreamSource (axis.py line 402) the variable _init_x is set to True. This forces all signals to X until they are used. 
What is the idea behind this?

From a source driver I would expect to output a valid state all the time.

**Comment by alexforencich** [comment]
It initializes tvalid to 0, and when tvalid is 0 the values of all of the other signals are irrelevant and should be ignored by downstream logic.  Is X propagation causing some sort of an issue with your design?
