### ISSUE TITLE
AxiStreamMonitor / AxiStreamSink: idle() not working as expected

### ISSUE THREAD

**Issue by Botnic** [alexforencich/cocotbext-axi#26]
While working with the AxiStreamMonitor / AxiStreamSink classes, I had the impression that the function 'def idle(self)' of these classes does not work as expected. I want to use it, to check if the bus is idle, all packets have arrived and the test can be terminated. 

The function is based on the self.active variable, but I have not found a situation when it would be set to true.
Did I miss something?

Thank you

**Comment by alexforencich** [comment]
Hmm, yes, it looks like that's not implemented properly.  I pretty much exclusively use send and recv so that code path has basically never been tested.  I'll take a look at getting that implemented properly.

**Comment by alexforencich** [comment]
Try the current version and see if it does what you need.

**Comment by Botnic** [comment]
Great! Works as expected!

Thanks a lot
