### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by Botnic** [alexforencich/cocotbext-axi#45]
According to the front page, the latest version is v0.1.16. But there is a tag v0.1.18 and also a commit with message [Release v0.1.18](https://github.com/alexforencich/cocotbext-axi/commit/7606d7d7bdc1721158cd0a9b409e3230c4a160dc)

What is the reason, why v0.1.18 has not been released completely?

**Comment by alexforencich** [comment]
0.1.18 is on pypi, maybe I forgot to create a "release" here

**Comment by Botnic** [comment]
Thank you for this fast reaction.

**Comment by alexforencich** [comment]
Sure.  Also, it looks like I should probably go ahead and cut another release soon as there are a number of changes that have been made subsequent to the release of 0.1.18.
