### ISSUE TITLE
Logging TX frame and RX frame

### ISSUE THREAD

**Issue by Lockedloop** [alexforencich/cocotbext-axi#48]
Logging TX frames and RX frames in `axis.py` would be much nicer using `self.log.debug` instead of `self.log.info`.

**Comment by vborchsh** [comment]
Hello,
You can set up the required level of logging in particular class with something like:

```
import logging
axis_sink.log.setLevel(logging.WARNING)
```

Of course, this line also block the other INFO messages, but still.

**Comment by Lockedloop** [comment]
Thanks for the reply, this helps.
