### ISSUE TITLE
Is the repo unmaintained / closed to new features?

### ISSUE THREAD

**Issue by ollie-etl** [alexforencich/cocotbext-axi#63]
I'm trying to ascertain the state of this repository. There are requests over 2 months old with no responses from the maintainer(s??). I'd like to understand if new features are welcome, and the maintainer is busy, or if new features are unwanted, and the PR's are ignored. 

Both are fine, I understand this is open source and have no expectations on the maintainer(s) or the scope of the repo, but a statement as the the status would clarify if forking is the right way to go.

Finally, I'd be happy to act as a maintainer if desired.

@alexforencich

**Comment by alexforencich** [comment]
I have just been super busy working on Corundum and haven't had time to properly engage with pull requests.  I'll take a look now.

**Comment by ollie-etl** [comment]
@alexforencich thank you for the confirmation. I follow the mailing lists for Corundum with interest.
