### ISSUE TITLE
Cocotb Scorebord 

### ISSUE THREAD

**Issue by silvan-hdl** [alexforencich/cocotbext-axi#7]
Hello Alex
First: Thank you for your great work! 
Is there a possibility to use the cocotb scorebord with this driver? (I try to use the AxiStream Monitor)
If not, are there plans to implement this? 

Thank you
Silvan

**Comment by alexforencich** [comment]
Well cocotb deprecated the scoreboard as it is poorly written and has a number of issues.  I also don't use it myself, so supporting it is not planned.  However, I may be open to considering it if you can motivate why it's a good idea, and if there is a replacement for the (now deprecated) cocotb scoreboard.

**Comment by silvan-hdl** [comment]
Hello Alex
Well I didn't know about the plan to retire the scoreboard. 
In this case, I should stop using it. 
Thank you

**Comment by alexforencich** [comment]
TBH, I'm actually not sure if they're retiring it completely, or spinning it out to a separate repo/package where it can be maintained separately from the core cocotb codebase.  At any rate, the scoreboard in its current form needs some work.
