### ISSUE TITLE
manually set tlast=1 when sending the last sample

### ISSUE THREAD

**Issue by thenameisT** [alexforencich/cocotbext-axi#71]
I am using AxiStreamSource to write to the DUT, I am sending 8 samples of 12 bits each and I want to set tlast high only after all the samples are written, how can I do it?

**Comment by alexforencich** [comment]
`tlast` is for framing.  So, send your samples as a "block" of 8 samples with a single call to `send`, and `tlast` will get set on the last sample.

**Comment by thenameisT** [comment]
I have a list containing around 5000 values. The following is how I am writing. 
for i in range (0,len(data_list)-1,1)
    write_data=data_list[i]
    await axi_source.write(write_data)
In here after 8 samples _tlast_ goes high, but I want it to be high after at 4999th data. How can I do that?

**Comment by alexforencich** [comment]
What about `await axi_source.send(data_list)`?  If you want to use `tlast` for framing, don't use `read()` and `write()`, instead use `send()` and `recv()`.

**Comment by thenameisT** [comment]
It’s still the same. tlast is going high for each 8 samples. I checked the axis.py file 
Isn’t it that write method calls send method?
Are both same ?
