### ISSUE TITLE
How possible ot use this to replace the commercial VIP in the future?

### ISSUE THREAD

**Issue by simdream** [alexforencich/cocotbext-axi#9]
From the documentation, seems like a very complete plan is there.

**Comment by alexforencich** [comment]
If it does what you need, just use it?  I'm not sure exactly what you're asking about.

**Comment by rodrigomelo9** [comment]
Hi @alexforencich this issue is not really an issue, it has not a clear explanation and is very old, I think it can be closed (I am trying to clean the issues section to detect the real issues).

**Comment by davekeeshan** [comment]
This issue if not closed should be moved to a [discussion](https://github.com/alexforencich/cocotbext-axi/discussions) topic (though it should be closed)

**Comment by alexforencich** [comment]
That's a good point, I'll close this for now and it can be re-opened later under discussions.
